name: release

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      release:
        description: 'Create a full release (not prerelease)'
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_SHA: ${{ github.sha }}
          RELEASE: ${{ inputs.release && '1' || '' }}
        run: make -f Makefile.cosmo release
